name: salem
channels:
  - conda-forge
dependencies:
  - python=3.5
  - six
  - numpy
  - scipy
  - pyproj
  - joblib
  - netCDF4
  - shapely
  - geopandas
  - rasterio
  - pandas
  - xarray
  - matplotlib
  - Pillow
  - descartes
  - cartopy
  - numpydoc
  - ipython=4.0.1
  - sphinx
  - pip:
    - motionless
    - sphinx-gallery
