name: salem
channels:
  - conda-forge
dependencies:
  - python
  - six
  - numpy
  - scipy
  - pyproj
  - joblib
  - netCDF4
  - shapely
  - geopandas
  - rasterio
  - pandas
  - xarray
  - matplotlib
  - Pillow
  - descartes
  - numpydoc
  - ipython=4.0.1
  - sphinx=1.2.3  # pin to avoid https://github.com/sphinx-doc/sphinx/issues/1822
  - pip:
    - git+https://github.com/fmaussion/motionless.git
